---
title: "PS811 Portfolio"
author: "David Bates"
output:
  html_document: 
    toc: true ## table of contents
    code_folding: hide
---
```{r setup, include=FALSE}
## Defaults for R chunks
knitr::opts_chunk$set(echo = TRUE, ## echo = TRUE means code will show
                      warning=FALSE, ## supress warnings and messages from R
                      message=FALSE,
                      fig.path='Figs/', ## where to save figures
                      fig.height = 3, ## default figure size (can differ in each chunk)
                      fig.width = 3)

## Add any R packages you require. 
## Here are some we will use in 811:
requires <- c("tidyverse", ## tidyverse includes dplyr and ggplot2
              "magrittr",
              "foreign",
              "readstata13",
              "here")

## Install any you don't have
to_install <- c(requires %in% rownames(installed.packages()) == FALSE)
install.packages(c(requires[to_install], "NA"), repos = "https://cloud.r-project.org/" )

## Load all required R packages
library(tidyverse)
library(ggplot2); theme_set(theme_minimal())
library(magrittr)
library(here)
```
<!-- The above header sets everything up. -->





<!-- Replace the below with bit about you. -->
##Research Interests

I am interested in international organizations, specifically regional organizations. I'm also interested in the role of international law in international relations.

##Questions I Hope to Answer
I'm curious about why and how states in a region become more federated or less federated, and why this varies across regions.

##Potential Methods
I'm interested in survey data to capture domestic opinions, data-as-text to analyze treaty language and discourse of leaders.

##Potentially relevant data:
Relevant data for these questions include:
 
1. Records of parliamentary meetings.

2. Speeches by leaders
 
3. Macroeconomic data
 
4. Migration data

5. Public opinion data
 
6. Interview data with elites and citizens.

Some potential datasets include the World Treaty Index, the UN Treaty Collection, and World Bank Data for macroeconomic indicators.